
version: '3.8'

services:
  prometheus-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prometheus-bot
    ports:
      - "9087:9087"
    restart: unless-stopped
    volumes:
      - ./config.yaml:/config.yaml
      - ./template.yaml:/template.yaml
    # Uncomment to enable debug mode
    # command: ["-d"]

    # Health check to ensure the service is running
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9087/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s